NovelNest/Controllers/BookController.cs
namespace NovelNest.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NovelNest.Core.Contracts;
    using NovelNest.Core.Extensions;
    using NovelNest.Core.Models.QueryModels.Book;
    using NovelNest.Core.Models.QueryModels.BookStore;
    using NovelNest.Core.Models.ViewModels.Book;
    using NovelNest.Core.Services;
    using System.Security.Claims;

    public class BookController : BaseController
    {
        private readonly IBookService bookService;
        private readonly IPublisherService publisherService;

        public BookController(IBookService bookService, IPublisherService publisherService)
        {
            this.bookService = bookService;
            this.publisherService = publisherService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery]AllBooksQueryModel model)
        {
            var allBooks = await bookService.AllAsync(
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllBookstoresWithBook(int id, [FromQuery] AllBookStoresQueryModel model)
        {
            var allEvents = await bookService.AllBookstoresWithBook(
                id,
                model.SearchTerm,
                model.Status,
                model.CurrentPage,
                model.BookStoresPerPage);

            model.TotalBookStoresCount = allEvents.TotalBookStoresCount;
            model.BookStores = allEvents.BookStores;

            return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(int id, string information)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBook = await bookService.DetailsAsync(id);

            if (information != currentBook.GetInformation())
            {
                return BadRequest();
            }

            return View(currentBook);
        }

        [HttpGet]
        public async Task<IActionResult> Mine(string id, [FromQuery] AllBooksQueryModel model)
        {
            var userId = User.Id();

            if (userId != id)
            {
                return Unauthorized();
            }

            var bookCollections = new AllBookCollectionsModel()
            {
                booksUserWantsToRead = await bookService.AllWantToReadBooksIdsByUserIdAsync(
                userId, model.Genre, model.CoverType, model.SearchTerm, model.Sorting, model.CurrentPage, model.BooksPerPage),

                booksUserCurrentlyReading = await bookService.AllCurrentlyReadingBooksIdsByUserIdAsync(
                    userId, model.Genre, model.CoverType, model.SearchTerm, model.Sorting, model.CurrentPage, model.BooksPerPage),

                booksUserRead = await bookService.AllReadBooksIdsByUserIdAsync(
                    userId, model.Genre, model.CoverType, model.SearchTerm, model.Sorting, model.CurrentPage, model.BooksPerPage)
            };

            return View(bookCollections);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsWantToRead(int id)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBook = await bookService.DetailsAsync(id);
            return View(currentBook);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsCurrentlyReading(int id)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBook = await bookService.DetailsAsync(id);
            return View(currentBook);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsRead(int id)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBook = await bookService.DetailsAsync(id);
            return View(currentBook);
        }

        [HttpGet]
        public async Task<IActionResult> WantToRead([FromQuery] AllBooksQueryModel model)
        {
            var userId = User.Id();

            var allBooks = await bookService.AllWantToReadBooksIdsByUserIdAsync(
                userId,
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> CurrentlyReading([FromQuery] AllBooksQueryModel model)
        {
            var userId = User.Id();

            var allBooks = await bookService.AllCurrentlyReadingBooksIdsByUserIdAsync(
                userId,
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Read([FromQuery] AllBooksQueryModel model)
        {
            var userId = User.Id();

            var allBooks = await bookService.AllReadBooksIdsByUserIdAsync(
                userId,
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddWantToRead(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }
            if (await bookService.BookIsInAnotherCollectionAsync(id, userId))
            {
                await bookService.RemoveBookFromAllCollectionsAsync(id, userId);
            }


            await bookService.AddWantToReadBookAsync(id, userId);
            return RedirectToAction(nameof(Mine), new { id = userId });
        }

        [HttpGet]
        public async Task<IActionResult> AddCurrentlyReading(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }
            if (await bookService.BookIsInAnotherCollectionAsync(id, userId))
            {
                await bookService.RemoveBookFromAllCollectionsAsync(id, userId);
            }

            await bookService.AddCurrentlyReadingBookAsync(id, userId);
            return RedirectToAction(nameof(Mine), new { id = userId });
        }

        [HttpGet]
        public async Task<IActionResult> AddRead(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }
            if (await bookService.BookIsInAnotherCollectionAsync(id, userId))
            {
                await bookService.RemoveBookFromAllCollectionsAsync(id, userId);
            }

            await bookService.AddReadBookAsync(id, userId);

            if (await bookService.FindBookReviewAsync(User.Id(), id) != null)
            {
                return RedirectToAction(nameof(Mine), new { id = userId });
            }

            return RedirectToAction(nameof(BookReviewQuestion), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> BookReviewQuestion(int id)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var bookReviewQuestion = await bookService.BookReviewQuestionAsync(id);

            return View(bookReviewQuestion);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveWantToRead(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id) || !await bookService.BookIsWantToReadAsync(id, userId))
            {
                return BadRequest();
            }

            await bookService.RemoveWantToReadBookAsync(id, userId);
            return RedirectToAction(nameof(WantToRead));
        }

        [HttpGet]
        public async Task<IActionResult> RemoveCurrentlyReading(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id) || !await bookService.BookIsCurrentlyReadingAsync(id, userId))
            {
                return BadRequest();
            }

NovelNest/Controllers/BookStoreController.cs
namespace NovelNest.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NovelNest.Core.Contracts;
    using NovelNest.Core.Extensions;
    using NovelNest.Core.Models.QueryModels.Book;
    using NovelNest.Core.Models.QueryModels.BookStore;

    public class BookStoreController : BaseController
    {
        private readonly IBookStoreService bookStoreService;
        private readonly IBookService bookService;

        public BookStoreController(IBookStoreService bookStoreService, IBookService bookService)
        {
            this.bookStoreService = bookStoreService;
            this.bookService = bookService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery] AllBookStoresQueryModel model)
        {
            var allEvents = await bookStoreService.AllAsync(
                model.SearchTerm,
                model.Status,
                model.CurrentPage,
                model.BookStoresPerPage);

            model.TotalBookStoresCount = allEvents.TotalBookStoresCount;
            model.BookStores = allEvents.BookStores;

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id, string information)
        {
            if (!await bookStoreService.BookStoreExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBookStore = await bookStoreService.DetailsAsync(id);

            if (information != currentBookStore.GetInformation())
            {
                return BadRequest();
            }

            return View(currentBookStore);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> AllBooks([FromQuery] AllBooksQueryModel model, int id)
        {
            var allBooks = await bookStoreService.AllBooksAsync(
                id,
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.BookStoreId = id;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }
    }
}

NovelNest/Views/BookStore/Add.cshtml
@model BookStoreAddViewModel

@{
    ViewBag.Title = "Добави Книжарница";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Add" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Name" class="form-label-add-edit"><bold>Име</bold></label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Location" class="form-label-add-edit"><bold>Локация</bold></label>
                <input asp-for="@Model.Location" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Location" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.OpeningTime" class="form-label-add-edit"><bold>Час на Отваряне</bold></label>
                <input asp-for="@Model.OpeningTime" class="form-control" aria-required="true" type="time" />
                <span asp-validation-for="@Model.OpeningTime" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ClosingTime" class="form-label-add-edit"><bold>Час на Затваряне</bold></label>
                <input asp-for="@Model.ClosingTime" class="form-control" aria-required="true" type="time" />
                <span asp-validation-for="@Model.ClosingTime" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Contact" class="form-label-add-edit"><bold>Контакт</bold></label>
                <input asp-for="@Model.Contact" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Contact" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label-add-edit"><bold>Снимка (Линк)</bold></label>
                <input asp-for="@Model.ImageUrl" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-success mb-2 w-100 p-3 fw-bold" type="submit" value="Добави" />
                <a asp-action="All" class="btn btn-secondary mb-1 w-100 p-3 fw-bold">Обратно към Всички</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NovelNest/Views/BookStore/All.cshtml
@model AllBookStoresQueryModel
@inject IPublisherService publisherService

@{
    ViewBag.Title = "Всички Книжарници";
}

<h2 class="text-center mt-3">@ViewBag.Title</h2>
<hr />

@if (await publisherService.ExistsByUserIdAsync(User.Id()))
{
    <div class="text-center mb-4">
        <a asp-controller="Publisher" asp-action="AddBookStore" class="btn btn-primary btn-lg">Добави Книжарница</a>
    </div>
}

<form method="get">
    <div class="row justify-content-center align-items-end">
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="SearchTerm"></label>
                <input asp-for="SearchTerm" class="form-control" placeholder="Търси...">
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="Status"></label>
                <select asp-for="Status" class="form-control">
                    <option value="0">Всички</option>
                    <option value="1">Отворени</option>
                    <option value="2">Затворени</option>
                </select>
            </div>
        </div>
        <div class="col-md-1">
            <input type="submit" value="Търси" class="btn btn-success w-100" />
        </div>
    </div>
</form>

@if (!Model.BookStores.Any())
{
    <h2 class="text-center mt-5">Няма намерени книжарници!</h2>
}
else
{
    <div class="row justify-content-center mt-5">
        @foreach (var bookStore in Model.BookStores)
        {
            <partial name="_BookStorePartial" model="@bookStore" />
        }
    </div>
    <partial name="_BookStorePagesPartial" model="@Model" />
}

NovelNest/Views/BookStore/AllBooks.cshtml
@model AllBooksQueryModel
@inject IPublisherService publisherService

@{
    ViewBag.Title = "Всички книги";
}

<h2 class="text-center mt-3">@ViewBag.Title</h2>
<hr />

@if (await publisherService.ExistsByUserIdAsync(User.Id()))
{
    <div class="text-center mb-4">
        <a asp-controller="Publisher" asp-action="SelectBookFromBookStore" asp-route-id="@Model.BookStoreId" class="btn btn-primary btn-lg">Добави Книга</a>
    </div>
}

<form method="get">
    <div class="row">
        <div class="form-group col-md-3">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control" placeholder="Търси...">
        </div>

        <div class="form-group col-md-2">
            <label asp-for="Sorting"></label>
            <select asp-for="Sorting" class="form-control">
                <option value="0">Най-скоро добавени</option>
                <option value="1">Най-късно добавени</option>
                <option value="2">Цена (Възходяща)</option>
                <option value="3">Цена (Низходяща)</option>
                <option value="4">Заглавие (Възходящо)</option>
                <option value="5">Заглавие (Низходящо)</option>
                <option value="6">Автор (Възходящ)</option>
                <option value="7">Автор (Низходящ)</option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label asp-for="Genre"></label>
            <select asp-for="Genre" class="form-control">
                <option value="">Всички</option>
                @foreach (var genre in Model.Genres)
                {
                    <option value="@genre">@genre</option>
                }
            </select>
        </div>

        <div class="form-group col-md-3">
            <label asp-for="CoverType"></label>
            <select asp-for="CoverType" class="form-control">
                <option value="">Всички</option>
                @foreach (var coverType in Model.CoverTypes)
                {
                    <option value="@coverType">@coverType</option>
                }
            </select>
        </div>

        <div class="col-md-1 d-flex align-items-end">
            <input type="submit" value="Търси" class="btn btn-success w-100" />
        </div>
    </div>
</form>

@if (!Model.Books.Any())
{
    <h2 class="text-center mt-5">Няма намерени книги!</h2>
}
else
{
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 mt-5">
        @foreach (var book in Model.Books)
        {
            <div class="col mb-4">
                <div class="card h-100 text-center">
                    <img class="card-img-top" src="@book.ImageUrl" alt="Book Image">
                    <div class="card-body">
                        <h4 class="card-title"><strong>@book.Title</strong></h4>
                        <p class="card-text"><strong>Автор:</strong> @book.Author</p>
                        <p class="card-text"><strong>Цена:</strong> @book.Price лв.</p>
                    </div>
                    <a asp-controller="Book" asp-action="Details" asp-route-information="@book.GetInformation()" asp-route-id="@book.Id" class="btn btn-warning mb-1 w-100 p-3 fw-bold">Виж Повече</a>

                    @if (await publisherService.ExistsByUserIdAsync(User.Id()))
                    {
                        <a asp-controller="Publisher" asp-action="RemoveBookFromBookStore" asp-route-id="@book.Id" asp-route-secondId="@Model.BookStoreId" class="btn btn-danger mb-1 w-100 p-3 fw-bold">Премахни от Книжарница</a>
                    }
                </div>
            </div>
        }
    </div>
    <partial name="_BookPagesPartial" model="@Model" />
}

NovelNest/Views/BookStore/Delete.cshtml
@model BookStoreDeleteViewModel

@{
    ViewBag.Title = "Изтрий Книжарница";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body text-center">
                    <img class="card-img-top" src="@Model.ImageUrl" alt="Article Image" style="max-width: 200px; height: auto;">
                    <h2 class="card-title" style="margin-top: 15px;">@Model.Name</h2>
                    <p class="text-danger mt-3">Сигурен ли си, че искаш да изтриеш тази книжарница?</p>
                </div>
                <div class="card-footer d-flex justify-content-center">
                    <form asp-action="DeleteConfirmed" method="post" class="col-12">
                        <input type="hidden" asp-for="Id" />
                        <a asp-action="Details" asp-route-id="@Model.Id" asp-route-information="@Model.GetInformation()" class="btn btn-secondary mb-1 w-100 p-3 fw-bold">Обратно</a>
                        <button type="submit" class="btn btn-danger mb-1 w-100 p-3 fw-bold">Изтрий</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    body {
        background-color: #f8f9fa;
    }

    .container {
        margin-top: 50px;
    }

    .card {
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .text-danger {
        color: #dc3545;
    }

    .btn-danger {
        background-color: #dc3545;
        border-color: #dc3545;
    }

    .btn-secondary {
        background-color: #6c757d;
        border-color: #6c757d;
    }
</style>

NovelNest/Views/BookStore/Details.cshtml
@model BookStoreDetailsViewModel
@inject IPublisherService publisherService

@{
    ViewBag.Title = "Детайли";
}
<h2 class="text-center mt-4 mb-3">@ViewBag.Title</h2>
<hr />

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 text-center">
            <img src="@Model.ImageUrl" class="img-fluid" alt="Book Image" style="max-width: 100%;" />
        </div>
        <div class="col-md-8">
            <h4>@Model.Name</h4>
            <p><strong>Локация:</strong> @Model.Location</p>
            <p><strong>Отваря:</strong> @Model.OpeningTime</p>
            <p><strong>Затваря:</strong> @Model.ClosingTime</p>
            <p>
                <strong>В момента:</strong>
                @if (Model.Status == "Отворено")
                {
                    <span class="text-success"><strong>Отворено</strong></span>
                }
                else
                {
                    <span class="text-danger"><strong>Затворено</strong></span>
                }
            </p>
            <p><strong>Контакт:</strong> @Model.Contact</p>
        </div>
    </div>

    <div class="text-center mt-1">
        <a asp-controller="BookStore" asp-action="All" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Обратно към Всички</a>
        <a asp-controller="BookStore" asp-action="AllBooks" asp-route-id="@Model.Id" class="btn btn-success mb-2 w-100 p-3 fw-bold">Виж всички налични книги</a>
    </div>

    @if (await publisherService.ExistsByUserIdAsync(User.Id()))
    {
        <hr />
        <div class="d-flex justify-content-center mt-1">
            <a asp-controller="Publisher" asp-action="EditBookStore" asp-route-id="@Model.Id" class="btn btn-primary mb-1 me-1 me-md-2 w-100 p-3 fw-bold">Редактирай</a>
            <a asp-controller="Publisher" asp-action="DeleteBookStore" asp-route-id="@Model.Id" class="btn btn-danger mb-1 me-1 me-md-2 w-100 p-3 fw-bold">Изтрий</a>
        </div>
    }
</div>

NovelNest/Views/BookStore/Edit.cshtml
@model BookStoreEditViewModel

@{
    ViewBag.Title = "Редактирай Книжарница";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Edit" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Name" class="form-label-add-edit"><bold>Име</bold></label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Location" class="form-label-add-edit"><bold>Локация</bold></label>
                <input asp-for="@Model.Location" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Location" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.OpeningTime" class="form-label-add-edit"><bold>Час на Отваряне</bold></label>
                <input asp-for="@Model.OpeningTime" class="form-control" aria-required="true" type="time" />
                <span asp-validation-for="@Model.OpeningTime" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ClosingTime" class="form-label-add-edit"><bold>Час на Затваряне</bold></label>
                <input asp-for="@Model.ClosingTime" class="form-control" aria-required="true" type="time" />
                <span asp-validation-for="@Model.ClosingTime" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Contact" class="form-label-add-edit"><bold>Контакт</bold></label>
                <input asp-for="@Model.Contact" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Contact" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label-add-edit"><bold>Снимка (Линк)</bold></label>
                <input asp-for="@Model.ImageUrl" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-success mb-2 w-100 p-3 fw-bold" type="submit" value="Редактирай" />
                <a asp-action="Details" asp-route-information="@Model.GetInformation()" asp-route-id="@Model.Id" class="btn btn-secondary mb-1 w-100 p-3 fw-bold">Обратно</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NovelNest/Views/BookStore/SelectBook.cshtml
@model AllBooksQueryModel
@inject IPublisherService publisherService

@{
    ViewBag.Title = "Всички книги";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />


<form method="get">
    <div class="row">
        <div class="form-group col-md-3">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control" placeholder="Търси...">
        </div>

        <div class="form-group col-md-2">
            <label asp-for="Sorting"></label>
            <select asp-for="Sorting" class="form-control">
                <option value="0">Най-скоро добавени</option>
                <option value="1">Най-късно добавени</option>
                <option value="2">Цена (Възходяща)</option>
                <option value="3">Цена (Низходяща)</option>
                <option value="4">Заглавие (Възходящо)</option>
                <option value="5">Заглавие (Низходящо)</option>
                <option value="6">Автор (Възходящ)</option>
                <option value="7">Автор (Низходящ)</option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label asp-for="Genre"></label>
            <select asp-for="Genre" class="form-control">
                <option value="">Всички</option>
                @foreach (var genre in Model.Genres)
                {
                    <option value="@genre">@genre</option>
                }
            </select>
        </div>

        <div class="form-group col-md-3">
            <label asp-for="CoverType"></label>
            <select asp-for="CoverType" class="form-control">
                <option value="">Всички</option>
                @foreach (var coverType in Model.CoverTypes)
                {
                    <option value="@coverType">@coverType</option>
                }
            </select>
        </div>

        <div class="col-md-1 d-flex align-items-end">
            <input type="submit" value="Търси" class="btn btn-success w-100" />
        </div>
    </div>
</form>

@if (!Model.Books.Any())
{
    <h2 class="text-center mt-5">Няма намерени книги!</h2>
}
else
{
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 mt-5">
        @foreach (var book in Model.Books)
        {
            <div class="col mb-4">
                <div class="card h-100 text-center">
                    <img class="card-img-top" src="@book.ImageUrl" alt="Book Image">
                    <div class="card-body">
                        <h4 class="card-title"><strong>@book.Title</strong></h4>
                        <p class="card-text"><strong>Автор:</strong> @book.Author</p>
                        <p class="card-text"><strong>Цена:</strong> @book.Price лв.</p>
                    </div>
                    @if (await publisherService.ExistsByIdAsync(User.Id()))
                    {
                        <a asp-controller="BookStore" asp-action="AddBook" asp-route-id="@book.Id" asp-route-secondId="@Model.BookStoreId" class="btn btn-success mb-1 w-100 p-3 fw-bold">Добави</a>
                    }
                </div>
            </div>
        }
    </div>
    <partial name="_BookPagesPartial" model="@Model" />
}