NovelNest/Controllers/ArticleController.cs
namespace NovelNest.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NovelNest.Core.Contracts;
    using NovelNest.Core.Extensions;
    using NovelNest.Core.Models.QueryModels.Article;
    using NovelNest.Core.Models.ViewModels.Article;
    using System.Security.Claims;

    public class ArticleController : BaseController
    {
        private readonly IArticleService articleService;
        private readonly IPublisherService publisherService;

        public ArticleController(IArticleService articleService, IPublisherService publisherService)
        {
            this.articleService = articleService;
            this.publisherService = publisherService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery]AllArticlesQueryModel model)
        {
            var allArticles = await articleService.AllAsync(
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.ArticlesPerPage);

            model.TotalArticlesCount = allArticles.TotalArticlesCount;
            model.Articles = allArticles.Articles;

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id, string information)
        {
            if (!await articleService.ArticleExistsAsync(id))
            {
                return BadRequest();
            }

            var currentArticle = await articleService.DetailsAsync(id);

            if (information != currentArticle.GetArticleInformation())
            {
                return BadRequest();
            }

            return View(currentArticle);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> AllComments(int id, [FromQuery] AllArticleCommentsQueryModel model)
        {
            var article = articleService.FindArticleByIdAsync(id).Result;
            var articleInfo = await articleService.DetailsAsync(id);

            var allArticleComments = await articleService.AllArticleCommentsAsync(
                id,
                article.Title,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.CommentsPerPage);

            model.TotalArticleCommentsCount = allArticleComments.TotalArticleCommentsCount;
            model.ArticleComments = allArticleComments.ArticleComments;
            model.ArticleId = id;
            model.ArticleTitle = article.Title;
            model.ArticleInfo = articleInfo.GetArticleInformation();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddComment(int id)
        {
            string userId = User.Id();

            var articleCommentForm = new ArticleCommentAddViewModel()
            {
                ArticleId = id,
                UserId = userId
            };

            return View(articleCommentForm);
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(ArticleCommentAddViewModel articleCommentForm)
        {
            if (!ModelState.IsValid)
            {
                return View(articleCommentForm);
            }

            int newArticleComment = await articleService.AddArticleCommentAsync(articleCommentForm, articleCommentForm.UserId, articleCommentForm.ArticleId);

            return RedirectToAction(nameof(AllComments), new { id = articleCommentForm.ArticleId });
        }

        [HttpGet]
        public async Task<IActionResult> EditComment(int id)
        {
            var comment = await articleService.FindArticleCommentByIdAsync(id);

            if (comment == null)
            {
                return BadRequest();
            }
            if (User.Id() != comment.UserId)
            {
                return Unauthorized();
            }

            var commentForm = await articleService.EditArticleCommentGetAsync(id);
            return View(commentForm);
        }

        [HttpPost]
        public async Task<IActionResult> EditComment(ArticleCommentEditViewModel commentForm)
        {
            if (commentForm == null)
            {
                return BadRequest();
            }
            if (User.Id() != commentForm.UserId)
            {
                return Unauthorized();
            }
            if (!ModelState.IsValid)
            {
                return View(commentForm);
            }

            await articleService.EditArticleCommentPostAsync(commentForm);
            return RedirectToAction(nameof(AllComments), new { id = commentForm.ArticleId });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteComment(int id)
        {
            var articleComment = await articleService.FindArticleCommentByIdAsync(id);

            if (articleComment == null)
            {
                return BadRequest();
            }
            if (articleComment.UserId != User.Id() && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var searchedArticleComment = await articleService.DeleteArticleCommentAsync(id);

            return View(searchedArticleComment);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCommentConfirmed(int commentId)
        {
            var bookReview = await articleService.FindArticleCommentByIdAsync(commentId);

            if (bookReview == null)
            {
                return BadRequest();
            }
            if (bookReview.UserId != User.Id() && !User.IsAdmin())
            {
                return Unauthorized();
            }


            return RedirectToAction(nameof(AllComments), new { id = await articleService.DeleteArticleCommentConfirmedAsync(commentId) });
        }
    }
}

NovelNest/Controllers/PublisherController.cs
namespace NovelNest.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using NovelNest.Attributes;
    using NovelNest.Core.Contracts;
    using NovelNest.Core.Extensions;
    using NovelNest.Core.Models.QueryModels.Book;
    using NovelNest.Core.Models.ViewModels.Article;
    using NovelNest.Core.Models.ViewModels.Book;
    using NovelNest.Core.Models.ViewModels.BookStore;
    using NovelNest.Core.Models.ViewModels.Event;
    using System.Security.Claims;

    public class PublisherController : BaseController
    {
        private readonly IPublisherService publisherService;
        private readonly IBookService bookService;
        private readonly IBookStoreService bookStoreService;
        private readonly IArticleService articleService;
        private readonly IEventService eventService;

        public PublisherController(IPublisherService publisherService, IBookService bookService,
            IBookStoreService bookStoreService, IArticleService articleService, IEventService eventService)
        {
            this.publisherService = publisherService;
            this.bookService = bookService;
            this.bookStoreService = bookStoreService;
            this.articleService = articleService;
            this.eventService=eventService;
        }

        //Books
        [HttpGet]
        [MustBePublisher]
        public async Task<IActionResult> AddBook()
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var bookForm = new BookAddViewModel()
            {
                Genres = await bookService.AllGenresAsync(),
                CoverTypes = await bookService.AllCoverTypesAsync(),
            };

            return View(bookForm);
        }

        [HttpPost]
        [MustBePublisher]
        public async Task<IActionResult> AddBook(BookAddViewModel bookForm)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (await bookService.GenreExistsAsync(bookForm.GenreId) == false)
            {
                ModelState.AddModelError(nameof(bookForm.GenreId), "Genre does not exist!");
            }
            else if (await bookService.CoverTypeExistsAsync(bookForm.CoverTypeId) == false)
            {
                ModelState.AddModelError(nameof(bookForm.CoverTypeId), "Cover Type does not exist!");
            }

            if (!ModelState.IsValid)
            {
                bookForm.Genres = await bookService.AllGenresAsync();
                bookForm.CoverTypes = await bookService.AllCoverTypesAsync();
                return View(bookForm);
            }

            int newBookId = await publisherService.AddBookAsync(bookForm);
            return RedirectToAction("All", "Book");
        }

        [HttpGet]
        [MustBePublisher]
        public async Task<IActionResult> EditBook(int id)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var bookForm = await publisherService.EditBookGetAsync(id);
            return View(bookForm);
        }

        [HttpPost]
        [MustBePublisher]
        public async Task<IActionResult> EditBook(BookEditViewModel bookForm)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (bookForm == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                bookForm.Genres = await bookService.AllGenresAsync();
                bookForm.CoverTypes = await bookService.AllCoverTypesAsync();

                return View(bookForm);
            }

            int id = bookForm.Id;
            await publisherService.EditBookPostAsync(bookForm);
            return RedirectToAction("Details", "Book", new { id, information = bookForm.GetInformation() });
        }

        [HttpGet]
        [MustBePublisher]
        public async Task<IActionResult> DeleteBook(int id)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var searchedBook = await publisherService.DeleteBookAsync(id);

            return View(searchedBook);
        }

        [HttpPost]
        [MustBePublisher]
        public async Task<IActionResult> DeleteBookConfirmed(int id)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            await publisherService.DeleteBookConfirmedAsync(id);

            return RedirectToAction("All", "Book");
        }

        //BookStores
        [HttpGet]
        [MustBePublisher]
        public async Task<IActionResult> AddBookStore()
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var bookStoreForm = new BookStoreAddViewModel();

            return View(bookStoreForm);
        }

        [HttpPost]
        [MustBePublisher]
        public async Task<IActionResult> AddBookStore(BookStoreAddViewModel bookStoreForm)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!ModelState.IsValid)
            {
                return View(bookStoreForm);
            }

            await publisherService.AddBookStoreAsync(bookStoreForm);
            return RedirectToAction("All", "BookStore");
        }

        [HttpGet]
        [MustBePublisher]
        public async Task<IActionResult> EditBookStore(int id)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await bookStoreService.BookStoreExistsAsync(id))
            {
                return BadRequest();
            }

            var bookStoreForm = await publisherService.EditBookStoreGetAsync(id);
            return View(bookStoreForm);
        }

        [HttpPost]
        [MustBePublisher]
        public async Task<IActionResult> EditBookStore(BookStoreEditViewModel bookStoreForm)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }

            if (bookStoreForm == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(bookStoreForm);
            }

            int id = bookStoreForm.Id;
            await publisherService.EditBookStorePostAsync(bookStoreForm);
            return RedirectToAction("Details", "BookStore", new { id, information = bookStoreForm.GetInformation() });
        }

        [HttpGet]
        [MustBePublisher]
        public async Task<IActionResult> DeleteBookStore(int id)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await bookStoreService.BookStoreExistsAsync(id))
            {
                return BadRequest();
            }

            var searchedBookStore = await publisherService.DeleteBookStoreAsync(id);

            return View(searchedBookStore);
        }

        [HttpPost]
        [MustBePublisher]
        public async Task<IActionResult> DeleteBookStoreConfirmed(int id)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await bookStoreService.BookStoreExistsAsync(id))
            {
                return BadRequest();
            }

            await publisherService.DeleteBookStoreConfirmedAsync(id);

            return RedirectToAction("All", "BookStore");
        }

        [HttpGet]
        [MustBePublisher]
        public async Task<IActionResult> SelectBookFromBookStore([FromQuery] AllBooksQueryModel model, int id)
        {
            if (await publisherService.ExistsByUserIdAsync(User.Id()) == false && !User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var allBooks = await publisherService.AllBooksToChooseAsync(
                id,
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.BookStoreId = id;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        [MustBePublisher]

NovelNest/Views/Article/Add.cshtml
@model ArticleAddViewModel

@{
    ViewBag.Title = "Добави Статия";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Add" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label-add-edit"><bold>Заглавие</bold></label>
                <input asp-for="@Model.Title" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Content" class="form-label-add-edit"><bold>Съдържание</bold></label>
                <input asp-for="@Model.Content" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Content" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label-add-edit"><bold>Снимка (Линк)</bold></label>
                <input asp-for="@Model.ImageUrl" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-success mb-2 w-100 p-3 fw-bold" type="submit" value="Добави" />
                <a asp-action="All" class="btn btn-secondary mb-1 w-100 p-3 fw-bold">Обратно към Всички</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NovelNest/Views/Article/AddComment.cshtml
@model ArticleCommentAddViewModel

@{
    ViewBag.Title = "Добави Коментар";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="AddComment" method="post">
            <input type="hidden" asp-for="ArticleId" value="@Model.ArticleId" />
            <input type="hidden" asp-for="UserId" value="@Model.UserId" />
            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label-add-edit"><bold>Заглавие</bold></label>
                <input asp-for="@Model.Title" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label-add-edit"><bold>Описание</bold></label>
                <textarea asp-for="@Model.Description" class="form-control" aria-required="true" rows="5"></textarea>
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-success mb-2 w-100 p-3 fw-bold" type="submit" value="Добави" />
                <a asp-action="All" class="btn btn-secondary mb-1 w-100 p-3 fw-bold">Обратно към Всички</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

NovelNest/Views/Article/All.cshtml
@model AllArticlesQueryModel
@inject IPublisherService publisherService

@{
    ViewBag.Title = "Всички Статии";
}

<h2 class="text-center mt-3">@ViewBag.Title</h2>
<hr />

@if (await publisherService.ExistsByUserIdAsync(User.Id()))
{
    <div class="text-center mb-4">
        <a asp-controller="Publisher" asp-action="AddArticle" class="btn btn-primary btn-lg">Добави Статия</a>
    </div>
}

<form method="get">
    <div class="row justify-content-center align-items-end">
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="SearchTerm"></label>
                <input asp-for="SearchTerm" class="form-control" placeholder="Търси...">
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="Sorting"></label>
                <select asp-for="Sorting" class="form-control">
                    <option value="0">Най-скоро добавени</option>
                    <option value="1">Най-късно добавени</option>
                    <option value="2">Най-големи</option>
                    <option value="3">Най-малки</option>
                </select>
            </div>
        </div>
        <div class="col-md-1">
            <input type="submit" value="Търси" class="btn btn-success w-100" />
        </div>
    </div>
</form>

@if (!Model.Articles.Any())
{
    <h2 class="text-center mt-5">Няма намерени статии!</h2>
}
else
{
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 mt-5">
        @foreach (var article in Model.Articles)
        {
            <partial name="_ArticlePartial" model="@article" />
        }
    </div>
    <partial name="_ArticlePagesPartial" model="@Model" />
}

NovelNest/Views/Article/AllComments.cshtml
@model AllArticleCommentsQueryModel

@{
    ViewBag.Title = "Всички Коментари";
}

@{
    var comment = Model.ArticleComments.FirstOrDefault(r => r.UserId == User.Id());
}

@if (!Model.ArticleComments.Any())
{
    <h2 class="text-center">Няма намерени коментари за</h2>
    <h2 class="text-center text-success">"@Model.ArticleTitle!"</h2>
    <div class="text-center mb-2 mt-4">
        <a asp-controller="Article" asp-action="AddComment" asp-route-id="@Model.ArticleId" class="btn btn-success btn-lg">Добави Коментар</a>
    </div>
    <div class="text-center mb-2 mt-2">
        <a asp-controller="Article" asp-action="Details" asp-route-id="@Model.ArticleId" asp-route-information="@Model.ArticleInfo" class="btn btn-warning btn-lg">Върни се към Статията</a>
    </div>
}
else
{
    <div class="text-center mb-2 mt-2">
        <a asp-controller="Article" asp-action="Details" asp-route-id="@Model.ArticleId" asp-route-information="@Model.ArticleInfo" class="btn btn-warning btn-lg">Върни се към Статията</a>
    </div>

    <hr />

    <h2 class="text-center">Всички Коментари за</h2>
    <h2 class="text-center">"@Model.ArticleTitle"</h2>

    <form method="get" style="margin-top: 50px;">
        <div class="row justify-content-center">
            <div class="form-group col-md-3">
                <label asp-for="SearchTerm"></label>
                <input asp-for="SearchTerm" class="form-control" placeholder="Търси...">
            </div>

            <div class="form-group col-md-2">
                <label asp-for="Sorting"></label>
                <select asp-for="Sorting" class="form-control">
                    <option value="0">Най-скоро добавени</option>
                    <option value="1">Най-късно добавени</option>
                </select>
            </div>

            <div class="col-md-1 d-flex align-items-end">
                <input type="submit" value="Търси" class="btn btn-success w-100" />
            </div>
        </div>
    </form>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-1 mt-3">
        @if (comment == null)
        {
            <h2 class="text-center">Моят Коментар</h2>
            <div class="text-center mb-4 mt-4">
                <a asp-controller="Article" asp-action="AddComment" asp-route-id="@Model.ArticleId" class="btn btn-primary btn-lg">Добави Коментар</a>
            </div>

            if (Model.ArticleComments.Count() == 0)
            {
                <h4 class="text-center text-secondary" style="margin-top: 50px;">За момента никой не е добавял коментар за тази статия!</h4>
            }
            else
            {
                <h2 class="text-center">Други Коментари</h2>
                @foreach (var currentComment in Model.ArticleComments)
                {
                    @if (currentComment.UserId == User.Id())
                    {
                        continue;
                    }
                    <partial name="_ArticleCommentPartial" model="@currentComment" />
                }
                <partial name="_ArticleCommentPagesPartial" model="@Model" />
            }
        }
        else
        {
            <h2 class="text-center">Моят Коментар</h2>
            <partial name="_ArticleCommentPartial" model="@comment" />

            if (Model.ArticleComments.Count() == 1)
            {
                <h4 class="text-center text-secondary" style="margin-top: 50px;">За момента никой друг не е добавял коментар за тази статия!</h4>
            }
            else
            {
                <h2 class="text-center">Други Коментари</h2>
                @foreach (var currentComment in Model.ArticleComments)
                {
                    @if (currentComment.UserId == User.Id())
                    {
                        continue;
                    }
                    <partial name="_ArticleCommentPartial" model="@currentComment" />
                }
                <partial name="_ArticleCommentPagesPartial" model="@Model" />
            }
        }
    </div>
}

NovelNest/Views/Article/Delete.cshtml
@model ArticleDeleteViewModel

@{
    ViewBag.Title = "Изтрий Статия";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body text-center">
                    <img class="card-img-top" src="@Model.ImageUrl" alt="Book Image" style="max-width: 200px; height: auto;">
                    <h2 class="card-title" style="margin-top: 15px;">@Model.Title</h2>
                    <h5 class="card-title" style="margin-top: 15px;">Прочитания: @Model.ViewsCount</h5>
                    <p class="text-danger mt-3">Сигурен ли си, че искаш да изтриеш тази статия?</p>
                </div>
                <div class="card-footer d-flex justify-content-center">
                    <form asp-action="DeleteConfirmed" method="post" class="col-12">
                        <input type="hidden" asp-for="Id" />
                        <a asp-action="Details" asp-route-id="@Model.Id" asp-route-information="@Model.GetArticleInformation()" class="btn btn-secondary mb-1 w-100 p-3 fw-bold">Обратно</a>
                        <button type="submit" class="btn btn-danger mb-1 w-100 p-3 fw-bold">Изтрий</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    body {
        background-color: #f8f9fa;
    }

    .container {
        margin-top: 50px;
    }

    .card {
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .text-danger {
        color: #dc3545;
    }

    .btn-danger {
        background-color: #dc3545;
        border-color: #dc3545;
    }

    .btn-secondary {
        background-color: #6c757d;
        border-color: #6c757d;
    }
</style>

NovelNest/Views/Article/DeleteComment.cshtml
@model ArticleCommentDeleteViewModel

@{
    ViewBag.Title = "Изтрий Коментар";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body text-center">
                    <h2 class="card-title text-danger" style="margin-top: 15px;">Сигурен ли си, че искаш да изтриеш своя коментар за тази статия?</h2>
                    <h2 class="card-title" style="margin-top: 15px;">"@Model.ArticleTitle"</h2>
                </div>
                <div class="card-footer d-flex justify-content-center">
                    <form asp-action="DeleteCommentConfirmed" method="post" class="col-12">
                        <input type="hidden" asp-for="CommentId" />
                        <a asp-action="AllComments" asp-route-id="@Model.ArticleId" class="btn btn-secondary mb-1 w-100 p-3 fw-bold">Не</a>
                        <button type="submit" class="btn btn-danger mb-1 w-100 p-3 fw-bold">Да</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

NovelNest/Views/Article/Details.cshtml
@model ArticleViewModel
@inject IPublisherService publisherService

@{
    ViewBag.Title = "Статии";
    CultureInfo.CurrentCulture = new System.Globalization.CultureInfo("en-EN");
}

<div class="container text-center mt-5">
    <div class="card">
        <div class="card-body">
            <img src="@Model.ImageUrl" alt="Article Image" class="img-fluid mb-3" />
            <h2 class="card-title">@Model.Title</h2>
            <p class="card-text"><strong>Публикувана:</strong> @Model.DatePublished.ToString("dd/MM/yyyy HH:mm")</p>
            <p class="card-text"><strong>Прочитания:</strong> @Model.ViewsCount</p>

            <div class="container-sm">
                <p>@Html.DisplayFor(model => model.Content)</p>
            </div>

            <div class="text-center mt-1">
                <a asp-controller="Article" asp-action="AllComments" asp-route-id="@Model.Id" class="btn btn-primary mb-2 w-100 p-3 fw-bold">Виж Всички Коментари</a>
                <a asp-controller="Article" asp-action="All" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Обратно към Всички Статии</a>
            </div>

            @if (await publisherService.ExistsByUserIdAsync(User.Id()))
            {
                <hr />
                <div class="d-flex justify-content-center mt-1">
                    <a asp-controller="Publisher" asp-action="EditArticle" asp-route-id="@Model.Id" class="btn btn-success mb-1 me-1 me-md-2 w-100 p-3 fw-bold">Редактирай</a>
                    <a asp-controller="Publisher" asp-action="DeleteArticle" asp-route-id="@Model.Id" class="btn btn-danger mb-1 me-1 me-md-2 w-100 p-3 fw-bold">Изтрий</a>
                </div>
            }
        </div>
    </div>
</div>

NovelNest/Views/Article/EditComment.cshtml
@model ArticleCommentEditViewModel

@{
    ViewBag.Title = "Редактирай Коментар";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="EditComment" method="post">
            <input type="hidden" asp-for="ArticleId" value="@Model.ArticleId" />
            <input type="hidden" asp-for="UserId" value="@Model.UserId" />
            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label-add-edit"><bold>Заглавие</bold></label>
                <input asp-for="@Model.Title" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label-add-edit"><bold>Описание</bold></label>
                <textarea asp-for="@Model.Description" class="form-control" aria-required="true" rows="5"></textarea>
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                @{
                    var id = Model.ArticleId;
                }
                <a asp-controller="Article" asp-action="AllComments" asp-route-id="@id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Обратно към Всички Коментари</a>
                <input class="btn btn-success mb-2 w-100 p-3 fw-bold" type="submit" value="Редактирай" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}