NovelNest/Controllers/ArticleController.cs
namespace NovelNest.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NovelNest.Core.Contracts;
    using NovelNest.Core.Extensions;
    using NovelNest.Core.Models.QueryModels.Article;
    using NovelNest.Core.Models.ViewModels.Article;
    using System.Security.Claims;

    public class ArticleController : BaseController
    {
        private readonly IArticleService articleService;
        private readonly IPublisherService publisherService;

        public ArticleController(IArticleService articleService, IPublisherService publisherService)
        {
            this.articleService = articleService;
            this.publisherService = publisherService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery]AllArticlesQueryModel model)
        {
            var allArticles = await articleService.AllAsync(
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.ArticlesPerPage);

            model.TotalArticlesCount = allArticles.TotalArticlesCount;
            model.Articles = allArticles.Articles;

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id, string information)
        {
            if (!await articleService.ArticleExistsAsync(id))
            {
                return BadRequest();
            }

            var currentArticle = await articleService.DetailsAsync(id);

            if (information != currentArticle.GetArticleInformation())
            {
                return BadRequest();
            }

            return View(currentArticle);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> AllComments(int id, [FromQuery] AllArticleCommentsQueryModel model)
        {
            var article = articleService.FindArticleByIdAsync(id).Result;
            var articleInfo = await articleService.DetailsAsync(id);

            var allArticleComments = await articleService.AllArticleCommentsAsync(
                id,
                article.Title,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.CommentsPerPage);

            model.TotalArticleCommentsCount = allArticleComments.TotalArticleCommentsCount;
            model.ArticleComments = allArticleComments.ArticleComments;
            model.ArticleId = id;
            model.ArticleTitle = article.Title;
            model.ArticleInfo = articleInfo.GetArticleInformation();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddComment(int id)
        {
            string userId = User.Id();

            var articleCommentForm = new ArticleCommentAddViewModel()
            {
                ArticleId = id,
                UserId = userId
            };

            return View(articleCommentForm);
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(ArticleCommentAddViewModel articleCommentForm)
        {
            if (!ModelState.IsValid)
            {
                return View(articleCommentForm);
            }

            int newArticleComment = await articleService.AddArticleCommentAsync(articleCommentForm, articleCommentForm.UserId, articleCommentForm.ArticleId);

            return RedirectToAction(nameof(AllComments), new { id = articleCommentForm.ArticleId });
        }

        [HttpGet]
        public async Task<IActionResult> EditComment(int id)
        {
            var comment = await articleService.FindArticleCommentByIdAsync(id);

            if (comment == null)
            {
                return BadRequest();
            }
            if (User.Id() != comment.UserId)
            {
                return Unauthorized();
            }

            var commentForm = await articleService.EditArticleCommentGetAsync(id);
            return View(commentForm);
        }

        [HttpPost]
        public async Task<IActionResult> EditComment(ArticleCommentEditViewModel commentForm)
        {
            if (commentForm == null)
            {
                return BadRequest();
            }
            if (User.Id() != commentForm.UserId)
            {
                return Unauthorized();
            }
            if (!ModelState.IsValid)
            {
                return View(commentForm);
            }

            await articleService.EditArticleCommentPostAsync(commentForm);
            return RedirectToAction(nameof(AllComments), new { id = commentForm.ArticleId });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteComment(int id)
        {
            var articleComment = await articleService.FindArticleCommentByIdAsync(id);

            if (articleComment == null)
            {
                return BadRequest();
            }
            if (articleComment.UserId != User.Id() && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var searchedArticleComment = await articleService.DeleteArticleCommentAsync(id);

            return View(searchedArticleComment);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCommentConfirmed(int commentId)
        {
            var bookReview = await articleService.FindArticleCommentByIdAsync(commentId);

            if (bookReview == null)
            {
                return BadRequest();
            }
            if (bookReview.UserId != User.Id() && !User.IsAdmin())
            {
                return Unauthorized();
            }


            return RedirectToAction(nameof(AllComments), new { id = await articleService.DeleteArticleCommentConfirmedAsync(commentId) });
        }
    }
}

NovelNest/Controllers/BookController.cs
namespace NovelNest.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NovelNest.Core.Contracts;
    using NovelNest.Core.Extensions;
    using NovelNest.Core.Models.QueryModels.Book;
    using NovelNest.Core.Models.QueryModels.BookStore;
    using NovelNest.Core.Models.ViewModels.Book;
    using NovelNest.Core.Services;
    using System.Security.Claims;

    public class BookController : BaseController
    {
        private readonly IBookService bookService;
        private readonly IPublisherService publisherService;

        public BookController(IBookService bookService, IPublisherService publisherService)
        {
            this.bookService = bookService;
            this.publisherService = publisherService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery]AllBooksQueryModel model)
        {
            var allBooks = await bookService.AllAsync(
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllBookstoresWithBook(int id, [FromQuery] AllBookStoresQueryModel model)
        {
            var allEvents = await bookService.AllBookstoresWithBook(
                id,
                model.SearchTerm,
                model.Status,
                model.CurrentPage,
                model.BookStoresPerPage);

            model.TotalBookStoresCount = allEvents.TotalBookStoresCount;
            model.BookStores = allEvents.BookStores;

            return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(int id, string information)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBook = await bookService.DetailsAsync(id);

            if (information != currentBook.GetInformation())
            {
                return BadRequest();
            }

            return View(currentBook);
        }

        [HttpGet]
        public async Task<IActionResult> Mine(string id, [FromQuery] AllBooksQueryModel model)
        {
            var userId = User.Id();

            if (userId != id)
            {
                return Unauthorized();
            }

            var bookCollections = new AllBookCollectionsModel()
            {
                booksUserWantsToRead = await bookService.AllWantToReadBooksIdsByUserIdAsync(
                userId, model.Genre, model.CoverType, model.SearchTerm, model.Sorting, model.CurrentPage, model.BooksPerPage),

                booksUserCurrentlyReading = await bookService.AllCurrentlyReadingBooksIdsByUserIdAsync(
                    userId, model.Genre, model.CoverType, model.SearchTerm, model.Sorting, model.CurrentPage, model.BooksPerPage),

                booksUserRead = await bookService.AllReadBooksIdsByUserIdAsync(
                    userId, model.Genre, model.CoverType, model.SearchTerm, model.Sorting, model.CurrentPage, model.BooksPerPage)
            };

            return View(bookCollections);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsWantToRead(int id)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBook = await bookService.DetailsAsync(id);
            return View(currentBook);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsCurrentlyReading(int id)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBook = await bookService.DetailsAsync(id);
            return View(currentBook);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsRead(int id)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var currentBook = await bookService.DetailsAsync(id);
            return View(currentBook);
        }

        [HttpGet]
        public async Task<IActionResult> WantToRead([FromQuery] AllBooksQueryModel model)
        {
            var userId = User.Id();

            var allBooks = await bookService.AllWantToReadBooksIdsByUserIdAsync(
                userId,
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> CurrentlyReading([FromQuery] AllBooksQueryModel model)
        {
            var userId = User.Id();

            var allBooks = await bookService.AllCurrentlyReadingBooksIdsByUserIdAsync(
                userId,
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Read([FromQuery] AllBooksQueryModel model)
        {
            var userId = User.Id();

            var allBooks = await bookService.AllReadBooksIdsByUserIdAsync(
                userId,
                model.Genre,
                model.CoverType,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.BooksPerPage);

            model.TotalBooksCount = allBooks.TotalBooksCount;
            model.Books = allBooks.Books;
            model.Genres = await bookService.AllGenresNamesAsync();
            model.CoverTypes = await bookService.AllCoverTypesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddWantToRead(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }
            if (await bookService.BookIsInAnotherCollectionAsync(id, userId))
            {
                await bookService.RemoveBookFromAllCollectionsAsync(id, userId);
            }


            await bookService.AddWantToReadBookAsync(id, userId);
            return RedirectToAction(nameof(Mine), new { id = userId });
        }

        [HttpGet]
        public async Task<IActionResult> AddCurrentlyReading(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }
            if (await bookService.BookIsInAnotherCollectionAsync(id, userId))
            {
                await bookService.RemoveBookFromAllCollectionsAsync(id, userId);
            }

            await bookService.AddCurrentlyReadingBookAsync(id, userId);
            return RedirectToAction(nameof(Mine), new { id = userId });
        }

        [HttpGet]
        public async Task<IActionResult> AddRead(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }
            if (await bookService.BookIsInAnotherCollectionAsync(id, userId))
            {
                await bookService.RemoveBookFromAllCollectionsAsync(id, userId);
            }

            await bookService.AddReadBookAsync(id, userId);

            if (await bookService.FindBookReviewAsync(User.Id(), id) != null)
            {
                return RedirectToAction(nameof(Mine), new { id = userId });
            }

            return RedirectToAction(nameof(BookReviewQuestion), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> BookReviewQuestion(int id)
        {
            if (!await bookService.BookExistsAsync(id))
            {
                return BadRequest();
            }

            var bookReviewQuestion = await bookService.BookReviewQuestionAsync(id);

            return View(bookReviewQuestion);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveWantToRead(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id) || !await bookService.BookIsWantToReadAsync(id, userId))
            {
                return BadRequest();
            }

            await bookService.RemoveWantToReadBookAsync(id, userId);
            return RedirectToAction(nameof(WantToRead));
        }

        [HttpGet]
        public async Task<IActionResult> RemoveCurrentlyReading(int id)
        {
            string userId = User.Id();

            if (!await bookService.BookExistsAsync(id) || !await bookService.BookIsCurrentlyReadingAsync(id, userId))
            {
                return BadRequest();
            }

NovelNest/Controllers/EventController.cs
namespace NovelNest.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NovelNest.Attributes;
    using NovelNest.Core.Contracts;
    using NovelNest.Core.Extensions;
    using NovelNest.Core.Models.QueryModels.Event;
    using NovelNest.Core.Models.ViewModels.Event;
    using System.Security.Claims;

    public class EventController : BaseController
    {
        private readonly IEventService eventService;

        public EventController(IEventService eventService)
        {
            this.eventService = eventService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery] AllEventsQueryModel model)
        {
            var allEvents = await eventService.AllAsync(
                model.SearchTerm,
                model.Sorting,
                model.Status,
                model.CurrentPage,
                model.EventsPerPage);

            model.TotalEventsCount = allEvents.TotalEventsCount;
            model.Events = allEvents.Events;

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id, string information)
        {
            if (!await eventService.EventExistsAsync(id))
            {
                return BadRequest();
            }

            var currentEvent = await eventService.DetailsAsync(id);

            if (information != currentEvent.GetInformation())
            {
                return BadRequest();
            }
            return View(currentEvent);
        }
    }
}

NovelNest/Views/Shared/_ArticleCommentPagesPartial.cshtml
@model AllArticleCommentsQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalArticleCommentsCount /
        Model.CommentsPerPage);
}

@{
    var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.ArticleComments.Any();
}

<div class="row justify-content-center mt-2">
    <div class="col-md-6 d-flex justify-content-between">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Article"
           asp-action="AllComments"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>

        <p class="align-self-center">Страница @Model.CurrentPage от @maxPage</p>

        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Article"
           asp-action="AllComments"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
</div>

NovelNest/Views/Shared/_ArticleCommentPartial.cshtml
@inject UserManager<ApplicationUser> UserManager
@model ArticleCommentServiceModel

@{
    var user = await UserManager.FindByIdAsync(Model.UserId);
    var currentUserName = user.FirstName + " " + user.LastName;
}

<div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 10px;">
    <div><strong>@currentUserName</strong></div>
    <div><strong>Заглавие:</strong> @Model.Title</div>
    <div><strong>Описание:</strong> @Model.Description</div>

    <div class="d-flex justify-content-center mt-3">
        @if (Model.UserId == UserManager.GetUserId(User) && User.IsAdmin())
        {
            <a asp-controller="Article" asp-action="EditComment" asp-route-id="@Model.Id" class="btn btn-secondary px-2 fw-bold me-2">Редактирай</a>
            <a asp-controller="Article" asp-action="DeleteComment" asp-route-id="@Model.Id" class="btn btn-danger px-2 fw-bold">Изтрий</a>
        }
        else if (User.IsAdmin())
        {
            <a asp-controller="Article" asp-action="DeleteComment" asp-route-id="@Model.Id" class="btn btn-danger px-2 fw-bold">Изтрий</a>
        }
        else if (Model.UserId == UserManager.GetUserId(User))
        {
            <a asp-controller="Article" asp-action="EditComment" asp-route-id="@Model.Id" class="btn btn-secondary px-2 fw-bold me-2">Редактирай</a>
            <a asp-controller="Article" asp-action="DeleteComment" asp-route-id="@Model.Id" class="btn btn-danger px-2 fw-bold">Изтрий</a>
        }
    </div>
</div>

NovelNest/Views/Shared/_ArticlePagesPartial.cshtml
@model AllArticlesQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalArticlesCount /
        Model.ArticlesPerPage);
}

@{
    var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Articles.Any();
}

<div class="row justify-content-center mt-2">
    <div class="col-md-6 d-flex justify-content-between">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Article"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>

        <p class="align-self-center">Страница @Model.CurrentPage от @maxPage</p>

        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Book"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
</div>

NovelNest/Views/Shared/_BookPagesPartial.cshtml
@model AllBooksQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalBooksCount /
        Model.BooksPerPage);
}

@{
    var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Books.Any();
}

<div class="row justify-content-center mt-2">
    <div class="col-md-6 d-flex justify-content-between">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Book"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-genre="@Model.Genre"
           asp-route-coverType="@Model.CoverType"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>

        <p class="align-self-center">Страница @Model.CurrentPage от @maxPage</p>

        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Book"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-genre="@Model.Genre"
           asp-route-coverType="@Model.CoverType"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
</div>

NovelNest/Views/Shared/_BookPartial.cshtml
@model BookServiceModel

<div class="col mb-4">
    <div class="card h-100 text-center">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Book Image">
        <div class="card-body">
            <h4 class="card-title"><strong>@Model.Title</strong></h4>
            <p class="card-text"><strong>Автор:</strong> @Model.Author</p>
            <p class="card-text"><strong>Цена:</strong> @Model.Price лв.</p>
        </div>
        <a asp-controller="Book" asp-action="Details" asp-route-information="@Model.GetInformation()" asp-route-id="@Model.Id" class="btn btn-warning mb-1 w-100 p-3 fw-bold">Виж Повече</a>
        <a asp-controller="Book" asp-action="AllBookstoresWithBook" asp-route-information="@Model.Id" asp-route-id="@Model.Id" class="btn btn-success mb-1 w-100 p-3 fw-bold">Виж Наличност по Книжарници</a>
    </div>
</div>

NovelNest/Views/Shared/_BookReviewPagesPartial.cshtml
@model AllBookReviewsQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalBookReviewsCount /
        Model.ReviewsPerPage);
}

@{
    var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.BookReviews.Any();
}

<div class="row justify-content-center mt-2">
    <div class="col-md-6 d-flex justify-content-between">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Book"
           asp-action="AllReviews"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>

        <p class="align-self-center">Страница @Model.CurrentPage от @maxPage</p>

        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Book"
           asp-action="AllReviews"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
</div>

NovelNest/Views/Shared/_BookReviewPartial.cshtml
@inject UserManager<ApplicationUser> UserManager
@model BookReviewServiceModel

@{
    var user = await UserManager.FindByIdAsync(Model.UserId);
    var currentUserName = user?.FirstName + " " + user.LastName;
}

<div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 10px;">
    <div><strong>@currentUserName</strong></div>
    <div>
         <strong>Оценка: </strong>
         @for (int i = 1; i <= Model.Rate; i++)
         {
            <span style="color: gold; font-size: 15px;">⭐</span>
         }
         (@Model.Rate от 10)
    </div>
    <div><strong>Заглавие:</strong> @Model.Title</div>
    <div><strong>Описание:</strong> @(Model.Description?.Length <= 300 ? Model.Description : Model.Description.Substring(0, 300) + (Model.Description.Length > 300 ? "..." : ""))</div>

    <div class="d-flex justify-content-center mt-3">
        @if (Model.Description.Length > 300)
        {
            <a asp-controller="Book" asp-action="BookReviewDetails" asp-route-id="@Model.Id" class="btn btn-warning px-2 fw-bold me-2">Виж Цялото Ревю</a>
        }

        @if (Model.UserId == UserManager.GetUserId(User) && User.IsAdmin())
        {
            <a asp-controller="Book" asp-action="EditBookReview" asp-route-id="@Model.Id" class="btn btn-secondary px-2 fw-bold me-2">Редактирай</a>
            <a asp-controller="Book" asp-action="DeleteBookReview" asp-route-id="@Model.Id" class="btn btn-danger px-2 fw-bold">Изтрий</a>
        }
        else if (User.IsAdmin())
        {
            <a asp-controller="Book" asp-action="DeleteBookReview" asp-route-id="@Model.Id" class="btn btn-danger px-2 fw-bold">Изтрий</a>
        }
        else if (Model.UserId == UserManager.GetUserId(User))
        {
            <a asp-controller="Book" asp-action="EditBookReview" asp-route-id="@Model.Id" class="btn btn-secondary px-2 fw-bold me-2">Редактирай</a>
            <a asp-controller="Book" asp-action="DeleteBookReview" asp-route-id="@Model.Id" class="btn btn-danger px-2 fw-bold">Изтрий</a>
        }
    </div>
</div>

NovelNest/Views/Shared/_BookStoresWithBookPagesPartial.cshtml
@model AllBookStoresQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalBookStoresCount /
        Model.BookStoresPerPage);
}

@{
    var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.BookStores.Any();
}

<div class="row justify-content-center mt-2">
    <div class="col-md-6 d-flex justify-content-between">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Book"
           asp-action="AllBookstoresWithBook"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"><<</a>

        <p class="align-self-center">Страница @Model.CurrentPage от @maxPage</p>

        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Book"
           asp-action="AllBookstoresWithBook"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm">>></a>
    </div>
</div>

NovelNest/Views/Shared/_EventPagesPartial.cshtml
@model AllEventsQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalEventsCount /
        Model.EventsPerPage);
}

@{
    var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Events.Any();
}

<div class="row justify-content-center mt-2">
    <div class="col-md-6 d-flex justify-content-between">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Event"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>

        <p class="align-self-center">Страница @Model.CurrentPage от @maxPage</p>

        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Event"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
</div>